### ISSUE TITLE
Stop using `overflow: scroll` anywhere

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/beta.rust-lang.org#402]
# Design Feature Request
## Summary
Please stop using `overflow: scroll` anywhere and use `overflow: auto` instead.

These are used at least on code boxes, but there's no reason to use `overflow: scroll` anywhere.

## Motivation
`overflow: scroll` causes scrollbars to always appear on windows and linux, even when the content is not scrollable, which is just a waste of screen space and ugly given the colourful theme.

## Drawbacks
None, unless someone prefers useless scrollbars to appear?

**Comment by enzozus** [comment]
The code boxes in most (all?) places don't have a maximum height set, so the vertical scrollbars (in Chrome) and the ugly weird scrolling corner (in Firefox) are completely unnecessary and can be removed by using `overflow-x: scroll` instead of `overflow: scroll`.

But yes, also use `auto` instead of scroll. This gets rid of the scrollbar in many places. Carefully adjusting the code examples should get rid of all the scrollbars actually, but it's probably a good idea to keep `overflow-x: auto` around when the width is restricted.

**Comment by meven** [comment]
Under linux + firefox
currently : overflow: scroll 
![screenshot_20181201_181307](https://user-images.githubusercontent.com/620941/49330867-ecb43c80-f594-11e8-868c-d4d4c3f9d582.png)
overflow : auto
![screenshot_20181201_181330](https://user-images.githubusercontent.com/620941/49330869-f178f080-f594-11e8-9de5-c5bd1c421133.png)

**Comment by chriskrycho** [comment]
Resolved in #522.
