### ISSUE TITLE
Too much different colors

### ISSUE THREAD

**Issue by Phaiax** [rust-lang/beta.rust-lang.org#421]
# Design Feature Request
## Summary
When browsing, I felt a bit overwhelmed by the many background color shifts.

There are (bgcolor, fontcolor, fancycolor):  (white-black-yellow), (turquoise-white-aubergine), (blue-white-purple), (black-white-yellow), (purple-white-aubergine). Especially the toggeling between dark and light style is irritating.

## Motivation
Using less color shifts within a single page or assigning meaning to the colors could lower the mental load experienced when browsing the site.

## Unresolved Questions
- Get more feedback about how others feel about this.

**Comment by PayasR** [comment]
Yes! +1 to this. Somehow, the site just doesn't feel 'serious' as a result of this. The colors are too bright and the contrast is way too much  to scroll down comfortably.

**Comment by rep-nop** [comment]
I agree, and frankly the color choices leave me a bit confused because they don't really seem to have a common theme so the entire page looks mighty awkward in my opinion. Would definitely rethink the color palette. The text offset from the background rectangle also looks strange, but maybe that's just me.

**Comment by PayasR** [comment]
The text offset from rectangle bugs me as well. If there's a box, there should be things _in_ that box maybe?

**Comment by rep-nop** [comment]
It looks _slightly_ better on a mobile layout from a quick view from the developer tools, but along with the font its super jarring and hard to read.

**Comment by ashleygwilliams** [comment]
hey! thanks for filing.

at this time we're not looking to remove the colors wholesale from the website. it is true though that some pages may have unfortunate color combinations, and we are open to hearing that feedback! if you could be specific about which pages you'd like to see changed and to what (giving the existing styles for sections)- we'd be very open to working on improving that! thanks :)

**Comment by rep-nop** [comment]
http://beta.rust-lang.org/ on the main page, the green, pink (... red?), and weirdly light-dark gray don't mesh very well. The black on yellow on white of "Rust in production" (no header links?) is way out of place. The colors in general are too light and don't carry much "weight" to them and feel way too comical with the font. Contribution page suffers from a weird Neopolitan ice cream scheme. There's others but that's my tl;dr basically.

**Comment by jonas-schievink** [comment]
FWIW we've discussed this in the office today and this seemed to be the most glaring issue most of us had with the new site. IMO just using one consistent backdrop would look much better than this, there's just *way* too much change in contrast.

**Comment by rep-nop** [comment]
@jonas-schievink 100% agree

**Comment by ashleygwilliams** [comment]
thanks for the feedback. if you'd like to open a PR to reaarange some of the color backdrops on other pages that'd be great and i can give feedback on the PR directly.

as i said previously, wholesale removing the colors is not currently up for discussion. closing this, and will give feedback on specific suggestions in PRs.

**Comment by TheZoq2** [comment]
I think most of the colours are fine, but the parts with the white text on top of pink/purple are pretty hard to read

**Comment by jonas-schievink** [comment]
@TheZoq2 Yeah, but that's https://github.com/rust-lang/beta.rust-lang.org/issues/408

**Comment by memoryruins** [comment]
I understand this issue is closed, but I did not not want to bombard the repo with yet another issue when this one is fitting. I tweaked these before finding the relevant issues, so the header underline change is more fitting to be discussed in #408, and is not the focus of the following screenshots.

Instead of removing the colors wholesale, we could try reducing the palette to be more in the spirit of the stable website while keeping the wonderful flexibility of the new layout :)

The following uses white, grey, and re-uses blue from the current stable website;

![screenshot 3894](https://user-images.githubusercontent.com/6868531/49270113-2d497400-f436-11e8-8b86-12ef87cad45b.png)

---

![screenshot 3900](https://user-images.githubusercontent.com/6868531/49270118-31759180-f436-11e8-8cae-8ba68e68a028.png)

---

![screenshot 3902](https://user-images.githubusercontent.com/6868531/49270120-33d7eb80-f436-11e8-9305-12dc1151957a.png)

^ unsure about using the blue for the full background, but was curious to see what it looked like re-used.

**Comment by memoryruins** [comment]
For the sake of showing different pages using their own variations reduced palettes:

![fvpcrlp](https://user-images.githubusercontent.com/6868531/49272098-4ce49a80-f43e-11e8-9c30-8392bb551dc3.png)

![screenshot 3906](https://user-images.githubusercontent.com/6868531/49272563-fbd5a600-f43f-11e8-9b76-41b5e8aa821e.png)

Background switches from white to grey then back to white:
![screenshot 3905](https://user-images.githubusercontent.com/6868531/49272553-f11b1100-f43f-11e8-8164-cbd0d19759c5.png)

This one uses both purple and green, rather than only one:
![screenshot 3909](https://user-images.githubusercontent.com/6868531/49272570-009a5a00-f440-11e8-9603-fb197a0f7f5c.png)

Not final proposed colors, more so proof of concept of less variation on individual pages.

**Comment by ashleygwilliams** [comment]
hey folks, this issue is closed. i am locking this, as there should not be continued conversation on this.
