### ISSUE TITLE
nitpick: The rust logo on the home page should not be a link

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/beta.rust-lang.org#536]
# Navigation Bug Report

## Page(s) Affected
- Only the home page

## What needs to be fixed?

> 7. Don’t include an active Home link on the homepage.
>  It’s confusing to have an active link to any given page on that page itself, and the homepage is no exception. Offer Home links only on interior pages. On the homepage, either clearly show Home in a selected state or do not present the Home link at all.

https://www.nngroup.com/articles/homepage-links/

## Suggested Improvement

Don't make it a link.

**Comment by chriskrycho** [comment]
Notably, Nielson Norman Group's *own website* violates this rule: its home page has links to the home page via both their logo and a "Home" link. I think the general pattern of web site design actually militates strongly *against* this suggestion, because most sites (whatever NNG thinks!) *do* have this pattern.
